### ISSUE TITLE
Active mode support for FTP Client

### ISSUE THREAD

**Issue by longxuanho** [patrickjuchli/basic-ftp#98] opened 2019-10-16 05:27 UTC
First of all, thanks for an excellent FTP package. I use it for some projects of mine, but I wonder how to retrieves data (list, get, etc.) from the FTP server using the active mode. Please provide a detail sample code and update your document for it.

Thanks.

**Comment by patrickjuchli** [comment] 2019-10-16 05:55
Duplicate of #25, no?

**Closed** 2019-10-16 07:11 UTC

**Comment by longxuanho** [comment] 2019-10-16 07:22
Sorry for the duplicated question. But can I ask one more?

The package works well with FTP server set up on Ubuntu `vsftpd` (listing files) but when I try to list file on the remote FTP server set up on the Windows Server (Cleo VLProxy 3.7.0.0), it returns an empty array. Can you point me out the problem?

```javascript
await client.access({
    host: |vsftpd_host",
    user: "user",
    password: "password",
    secure: false
})

await client.list("/dir")
// Return the result with all files listed

await client.access({
    host: |cleo_vlproxy",
    user: "user",
    password: "password",
    secure: false
})

await client.list("/dir")
// Return just [ ]
```

**Comment by patrickjuchli** [comment] 2019-10-16 08:05
Can you open this as a separate issue? It's possible that this is a real problem and using a dedicated issue is better documentation.

(Use `client.ftp.verbose` and paste the complete log. I can't help you without this.)
