### ISSUE TITLE
Source.once is not a function

### ISSUE THREAD

**Issue by yzpaul** [patrickjuchli/basic-ftp#97] opened 2019-10-16 02:26 UTC
**Describe the bug**
When I try to transfer a file I get this error. I can list directories correctly which seems to rule out connection issues. 

**Example code**

// note that res= data being transferred (passed in as a string)
var ftpWrite = async function(filename,twodigitcoid,res){
  let filepath = `D:/EIS_97/incoming/latest${twodigitcoid}/${filename}`
  try {
   console.log(`FTP file to: ${filepath}\nsending data of length: ${res.length}\n\n`)
    
    console.log('starting client')
    const client = new ftp.Client();
    client.ftp.verbose = true

    await client.access({
      host: "my ip",
      user: "ftpUser",
      password: "my pwd",
      port: 21,
      secure: false
    });

    await client.upload(res, filepath);
    console.log('file uploaded')
    await client.rename(filepath, filepath + '.fil')
    console.log('file renamed')
    return 'success'
  } catch (e) {
    console.log('error writing via FTP: ' + e + ' to path: ' + filepath)
    return 'ftp err';
  }
};

**Console output**
Connected to 13.56.83.249:21
< 220 Microsoft FTP Service
Login security: No encryption
> USER ftpUser
< 331 Password required
> PASS ###
< 230 User logged in.
> TYPE I
< 200 Type set to I.
> STRU F
< 200 STRU F ok.
> OPTS UTF8 ON
< 200 OPTS UTF8 command successful - UTF8 encoding now ON.
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 501 Option not supported.
error writing via FTP: TypeError: source.once is not a function

**Which version of Node.js are you using?**
e.g. Node 10.16.3

**Additional context**
running on a barebones AWS linux instance. Sending files to an AWS Windows machine.

**Comment by patrickjuchli** [comment] 2019-10-16 06:00
Duplicate of #66, no?

**Closed** 2019-10-16 20:41 UTC

**Comment by patrickjuchli** [comment] 2019-10-22 09:35
In 4.3.0 you can now use file paths directly.
