### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by dmitriyshashkin** [patrickjuchli/basic-ftp#166] opened 2020-11-15 18:19 UTC
**Describe the bug**
I'm trying to connect to bunny-cdn FTP(https://bunnycdn.com/) using the code from the example https://github.com/patrickjuchli/basic-ftp#introduction 

And I get the following error:

`Error: Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:*.storage.bunnycdn.com, DNS:storage.bunnycdn.com" (data socket)`

Yet the host I specified is different, I used "storage.bunnycdn.com" as the host value. Where does the "localhost" come from?

I'm able to connect to the same server using the same settings when using other FTP clients

**Example code**
```
async function example() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        await client.access({
            host: "storage.bunnycdn.com",
            user: "USER",
            password: "PASS",
            secure: true
        })
        console.log(await client.list())

    }
    catch(err) {
        console.log(err)
    }
    client.close()
}

```

**Console output**
```
Connected to 116.202.118.194:21 (No encryption)
< 220 Service Ready.

> AUTH TLS
< 234 Enabling TLS Connection

Control socket is using: TLSv1.2
Login security: TLSv1.2
> USER ###
< 331 Username ok, need password

> PASS ###
< 230 User logged in

> TYPE I
< 200 Type set to Image

> STRU F
< 200 Command OK

> OPTS UTF8 ON
< 200 Command okay.

> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 501 Syntax error in parameters or arguments.

> PBSZ 0
< 200 OK

> PROT P
< 200 OK

Trying to find optimal transfer strategy...
> EPSV
< 502 Command not implemented

> PASV
< 227 Entering Passive Mode (116,202,118,194,51,220)

Optimal transfer strategy found.
> MLSD /
< 502 Command not implemented

> PASV
< 227 Entering Passive Mode (116,202,118,194,79,182)

> LIST -a /
< 150 Opening Image mode data transfer for LIST

Downloading from 116.202.118.194:20406 (TLSv1.3)
Error [ERR_TLS_CERT_ALTNAME_INVALID] [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.storage.bunnycdn.com, DNS:storage.bunnycdn.com
```

**Which version of Node.js are you using?**
15.2

**Comment by patrickjuchli** [comment] 2020-11-26 07:50
Seeing the same thing with the same FTP server at bunny. Not sure what the problem is at this point.

**Comment by patrickjuchli** [comment] 2021-01-30 12:19
Any news here from your side? How have you dealt with this problem, are you using another library or did the problem disappear?

**Comment by alandoherty** [comment] 2021-02-15 20:24
@patrickjuchli When using explicit TLS the library doesn't automatically set the TLS `ConnectionOptions.host` field to the host specified in the connection. This code should fix your problem and I'll make a pull request to fix this, ran into exactly the same problem.

```js
await client.access({
  host: "myhost.potato.com",
  user: "user",
  password: "pswd",
  secure: true,
  secureOptions: {
    host: "myhost.potato.com"
  }
})
```

**Comment by patrickjuchli** [comment] 2021-03-24 17:08
@alandoherty great, will comment in PR. But it would be nice to know why exactly this error shows up in – I believe – rare or specific cases. Why do we sometimes have to set `host` explicitly while it works in most cases?

**Comment by alandoherty** [comment] 2021-03-24 17:22
@patrickjuchli The default for the `host` field in `secureOptions` is "localhost" so that might explain why it works in local tests if you're connecting to ftps://localhost anyway.

**Comment by patrickjuchli** [comment] 2021-03-24 17:56
That can't be it, this library has been used quite a lot in production. There is clearly something wrong but I can't see a pattern yet.

**Comment by patrickjuchli** [comment] 2021-03-24 21:08
@alandoherty, your potential fix has been released in 4.6.4, let me know if it works for you.

**Comment by patrickjuchli** [comment] 2021-03-26 19:45
Fixes this specific issue for bunnycdn. There is another one though connected to this server tracked here #187

**Closed by patrickjuchli** 2021-03-26 19:45 UTC

**Comment by loilo** [comment] 2021-04-13 18:15
I was seeing the same issue and it cause quite a lot of headache, but I have found another condition which can cause this issue: [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). I'm noting this here fore possible future visitors of this issue.

```
Hostname/IP does not match certificate's altnames: Host: imaginary-domain.com. is not in the cert's altnames: DNS:*.hostserv.eu, DNS:hostserv.eu
```

The connection attempt was refused until I explicitly set the `secureOptions.servername` to the domain of the hoster where my domain is registered (hostserv.eu in that case, the altname reported in the error):

```js
await client.access({
  host: 'imaginary-domain.com',
  port: 21,
  secure: true,
  secureOptions: {
    servername: 'hostserv.eu'
  }
})
```

Unfortunately, I'm an absolute beginner regarding networking stuff, so I could, for the love of me, not figure out how to programmatically determine the correct `servername` option.

But because my `host` is not hardcoded, I needed a workaround, so I solved the problem with a workaround: When the `ERR_TLS_CERT_ALTNAME_INVALID` error occurs, I parse the cert's altnames from the `error.reason` and do another connection attempt with the `servername` set to the first altname (filtering out wildcard domains first, of course).

This has served me well so far, but I don't know if this is correct in any way — or if the match between the cert's altnames and the `servername` option is just a happy coincidence. Maybe someone with more experience can judge this.

FWIW, here's the code I'm currently using to connect the client — please consider that as long as nobody with some experience can confirm that this is how it *should* work, this is probably just a "lucky punch" if it works:

```js
async function connect(client, options) {
  try {
    return await client.access(options)
  } catch (error) {
    // Bail if not a secure connection
    if (!options.secure) {
      throw error
    }

    // Only attempt a second time if the altname error is thrown
    if (error.code === 'ERR_TLS_CERT_ALTNAME_INVALID') {
      client.close()

      // Try to use the first mentioned (non-wildcard) altname as servername
      let [servername] = error.reason.match(/(?<=DNS:)[a-z0-9.-]+/i) ?? []

      if (dnsMatch) {
        return await client.access({
          ...options,
          secureOptions: {
            ...(options.secureOptions ?? {}),
            servername,
          },
        })
      }
    }

    throw error
  }
}
```
