### ISSUE TITLE
Add full file path in info from trackProgress

### ISSUE THREAD

**Issue by Satyam** [patrickjuchli/basic-ftp#238] opened 2023-08-30 17:28 UTC
Feature Request:

It would be great to have the full path to the file along the rest of the info object in `trackProgress`.   

Most web sites would have lots of files called `index.html` thus providing only the file name doesn't help much.

Thanks

**Comment by patrickjuchli** [comment] 2023-08-31 20:48
Duplicate of #137

**Closed by patrickjuchli** 2023-08-31 20:48 UTC
