### ISSUE TITLE
This socket is closed

### ISSUE THREAD

**Issue by AxelTerizaki** [patrickjuchli/basic-ftp#18] opened 2018-07-08 20:29 UTC
Hello.

I'm having several users reporting an error at some point in my app when downloading the updates by FTP.

Updates consist of many video files, and thus can take a long time to download. I'm trying to pinpoint what's causing it exactly but thi sis very hard to diagnose and I realize I'm not being very helpful by saying that : it works very well for me (able to download via FTP for hours) and for others it fails with an error like that in the middle of a download.

The FTP server we connect to is a standard Pure-FTPd on an Ubuntu 16.04

If I can help further, I'd love to as this has been bugging me for a bit.

**Comment by AxelTerizaki** [comment] 2018-07-08 20:42
https://cdn.discordapp.com/attachments/268806084054089728/465617611665833984/unknown.png

Here's a screenshot from one of my users running into the issue.

**Comment by TigaxMT** [comment] 2018-07-09 02:12
Are they always the same videos that make the error trigger? 

Check if your videos inside your FTP have the right permissions (root permissions trigger errors, root permissions triggers errors, I know because this happened to me several times).

**Comment by patrickjuchli** [comment] 2018-07-09 11:34
Hi @AxelTerizaki, I have some questions:

- Everybody is accessing the same FTP server with the same files?
- Everybody is doing so using an executable that contains a Node.js runtime (KaraokeMugen.exe? Which version?) or are they using their own runtime? 
- For some people download fails. Mostly after quite some time passed or e.g. within 10 minutes?
- It's a bit unfortunate that we don't see which socket exactly is closed, the control or data connection. I should improve error reporting for the next version. Do you have an example of an exception with a full stack dump?
- Are you using FTPS or FTP?

Downloading a file happens using a dedicated _data connection_. During this download, the _control connection_ used for FTP commands sits idle. It can happen that a router somewhere shuts down this control connection after some time. This is not standard behaviour but it can happen. It's difficult to say whether this is what is happening here. Any further information will be helpful, thanks.

On a side note: You should always assume that very large downloads might fail. You should try to resume failed downloads specifying an offset `startAt` in bytes when using `download()`:

`download(writableStream, remoteFilename, startAt = 0): Promise<Response>`

**Comment by AxelTerizaki** [comment] 2018-07-09 11:40
1) Yes
2) Some people use the executable version which contains the nodejs runtime, and some others use their own runtime, but the user who tested it for me yesterday tried with either version.
3) It fails after some time has passed, we'll make some more tests this evening to tell if it's a set time limit or something at random (in pure-ftpd's config, the default timeout is 15 minutes, and the connection failure from our end happens way before that)
4) I'll try to provide a full stack dump next time.
5) FTP

I can try to implement a retry mechanism, I'll look ingo this. Thanks for the tip.

**Comment by AxelTerizaki** [comment] 2018-07-12 08:43
Here's another test we just did.

As you can see the first two files download well, the third one stalls at some point and an error is displayed then :

![screenshot_20180712_100233](https://user-images.githubusercontent.com/4531597/42622261-45217026-85c0-11e8-87eb-e6473485a9e6.png)
![unknown](https://user-images.githubusercontent.com/4531597/42622297-5bf5f77c-85c0-11e8-856a-eec25993584f.png)

**Comment by AxelTerizaki** [comment] 2018-07-12 09:20
![unknown2](https://user-images.githubusercontent.com/4531597/42624314-62363bd8-85c5-11e8-9e88-5d406a2aebc2.png)

I just made it display the error returned when one of the connections dies.

I implemented a retry mechanic which seems to allow files to download properly though, as it retries for a while and reconnects to the FTP if there's an error.

Yet this seems pretty weird and only occurs for some people.

**Comment by patrickjuchli** [comment] 2018-07-12 10:41
Right, the timeout for the data connection is the root cause.

If a download is stalling, you'll eventually run into a timeout exception. This is expected behaviour from the client. The question is now, why the download is stalling. There is either something going on at the FTP server or there is just simply an issue with the connection – this can totally happen. Do you have any server logs, do you have access to them?

At this moment, this doesn't look like a client issue to me.

**Comment by patrickjuchli** [comment] 2018-07-12 11:10
To clarify: If a timeout occurs the client fails completely. It does so because after the timeout expires, the client can't know in which state the server is. Maybe stuff is still on its way. Or not. We don't know, that's why we have a timeout on the client side. To continue as if nothing happened could lead to unpredictable behaviour when the "stuff" eventually does arrive anyway while the client is busy with something entirely different.

**Comment by AxelTerizaki** [comment] 2018-07-12 16:08
I understand what you're saying. 

However, there must be something, somewhere, that triggers that timeout, because my test user just tried with a regular FTP client and managed to grab 90 downloads without any issues.

Maybe there's something wrong in my code too, but I have absolutely no idea what it could be though...

**Comment by patrickjuchli** [comment] 2018-07-12 17:58
Do you have access to the FTP server? Can you have a look at its logs? If the download has been stalled for a reason, it might be logged there.

**Comment by patrickjuchli** [comment] 2018-07-13 15:08
Do you know what the "regular FTP client" is doing? Maybe it retries stalled downloads as well? Also, it did work for you. What percentage of users have problems? Why did it work for you? Is this related to connection quality?

If there is no additional info coming in I'll have to close this ticket.

**Comment by AxelTerizaki** [comment] 2018-07-13 15:30
We're supposed to redo a test this evening so I can listen on the debug logs of pure-ftpd.

As for your other questions:

- Hard to tell which percentage of users as I don't have telemetry yet in the app. However, at least a five or six people came to me with the issue. According to my web server stats about 42 people have downloaded the latest stable version this month. And I'm not counting people who might have the issue but haven't reported it.
- I suppose this is related to connection quality and peering. The server is in a datacenter and like all datacenters, it depends on peering between your ISP and the company running the datacenter, the routers it goes through, etc.
- For me it works fine. It isn't related to speed, as the user testing it with me right now has optical fiber and I have regular DSL. 
- I asked which desktop FTP client he used, I'll tell you once I know.

this evening we're going to make tests with both the desktop FTP client and my app and see what happens on pure-ftp's side. Then we'll be able to compare and see what might be wrong.

I understand this is a complex issue to tackle on as it involves many parameters.

**Comment by AxelTerizaki** [comment] 2018-07-16 21:20
Sorry for the wait.

We redid a series of tests. During the weekend, I rewrote the downloader to user webdav+http to see if it was a real connection issue or not.

With the http version, things download well, we left it on for like 10 minutes or so.

Then I made the user switch back to the FTP code and like we thought, it crashed 5 or so minutes after launch.

Here are logs from pure-ftpd : 

```
Jul 16 22:55:45 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [INFO] New connection from xxx.xxx.xxx.xxx.rev.sfr.net
Jul 16 22:55:45 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [user] [kmvideos]
Jul 16 22:55:45 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [pass] [<*>]
Jul 16 22:55:45 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [INFO] kmvideos is now logged in
Jul 16 22:55:45 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [type] [I]
Jul 16 22:55:45 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [stru] [F]

...

Jul 16 22:58:23 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [epsv] []
Jul 16 22:58:23 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [retr] [JAP - Bakemonogatari - ED - Kimi no Shiranai Monogatari ~ Nadeko Vers..mp4]
Jul 16 22:59:24 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//JAP - Bakemonogatari - ED - Kimi no Shiranai Monogatari ~ Nadeko Vers..mp4 downloaded  (28835840 bytes, 464.97KB/sec)
Jul 16 22:59:24 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [INFO] Logout.

```

Apparently the connection ends after a bit. The file appears downloaded, however, the size is wrong, as the file is supposed to be bigger : 

```
-rw-r--r-- 1 rinchama vip 43884512 juil. 15 17:09 /home/aterizak/karaokemugen/app/data/medias/JAP - Bakemonogatari - ED - Kimi no Shiranai Monogatari ~ Nadeko Vers..mp4
```

Note that there's a speed slowdown for some reason (probably ISP throttling?) on the last file. All other files are downloaded at high speed.

I then made the user do another test, this time with filezilla, and it seems it worked for a longer period of time. We didn't go beyond 5-10 minutes. What we noticed however, were these same slowdowns from time to time, but nothing that cut the connection.

Here are the logs with FileZilla : 

```
Jul 16 23:07:32 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [INFO] New connection from xxx.xxx.xxx.xxx..rev.sfr.net
Jul 16 23:07:32 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [auth] [TLS]
Jul 16 23:07:32 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [auth] [SSL]
Jul 16 23:07:32 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [user] [kmvideos]
Jul 16 23:07:32 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pass] [<*>]
Jul 16 23:07:33 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx..rev.sfr.net) [INFO] kmvideos is now logged in
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [opts] [UTF8 ON]
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [cwd] [/]
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [type] [I]
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [rest] [12318188]
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] Restarting at 12318188
Jul 16 23:07:33 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Hellsing Ultimate - ED4 - Das Engellandlied.mkv]
Jul 16 23:07:34 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Hellsing Ultimate - ED4 - Das Engellandlied.mkv downloaded  (31488805 bytes, 17964.26KB/sec)
Jul 16 23:07:34 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:34 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [rest] [0]
Jul 16 23:07:35 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Owarimonogatari - OP4 - mein schatz.mp4]
Jul 16 23:07:35 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Owarimonogatari - OP4 - mein schatz.mp4 downloaded  (12245371 bytes, 38756.29KB/sec)
Jul 16 23:07:35 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:35 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Pretty Cure - OP - Nur wir Beide.avi]
Jul 16 23:07:35 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Pretty Cure - OP - Nur wir Beide.avi downloaded  (24195128 bytes, 46143.68KB/sec)
Jul 16 23:07:36 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:36 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Shin Kidou Senki Gundam W - OP.mkv]
Jul 16 23:07:36 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Shin Kidou Senki Gundam W - OP.mkv downloaded  (44269650 bytes, 53924.84KB/sec)
Jul 16 23:07:36 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:37 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Shingeki no Kyojin Kuinaki Sentaku - IN - So ist es immer.mkv]
Jul 16 23:07:37 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Shingeki no Kyojin Kuinaki Sentaku - IN - So ist es immer.mkv downloaded  (16398945 bytes, 23288.37KB/sec)
Jul 16 23:07:37 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:37 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Strike Witches - AMV - Erika.avi]
Jul 16 23:07:38 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Strike Witches - AMV - Erika.avi downloaded  (14419628 bytes, 53029.28KB/sec)
Jul 16 23:07:38 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:38 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ANG - ACCA 13-ku Kansatsuka - OP - Shadow and Truth.mp4]
Jul 16 23:07:40 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ANG - ACCA 13-ku Kansatsuka - OP - Shadow and Truth.mp4 downloaded  (57917805 bytes, 23299.49KB/sec)
Jul 16 23:07:41 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Hellsing Ultimate - ED4 - Das Engellandlied.mkv downloaded  (15204352 bytes, 255.51KB/sec)
Jul 16 23:07:41 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [INFO] Logout.
Jul 16 23:07:55 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:07:55 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [rest] [41856740]
Jul 16 23:07:55 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] Restarting at 41856740
Jul 16 23:07:55 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [DEBUG] Command [retr] [ALL - Kampfer - IN - Ode an die Freude.avi]
Jul 16 23:07:56 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ALL - Kampfer - IN - Ode an die Freude.avi downloaded  (7129584 bytes, 5153.02KB/sec)
Jul 16 23:08:04 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx..rev.sfr.net) [INFO] Logout.
```

Not sure if this is related, but Filezilla seems to be using pasv instead of epsv on basic-ftp's end...

For now I'm leaving the http+webdav method in place, but I'm going to eventually put basic-ftp back in because I'd like to offer users the choice of which transfer protocol they wish to use.

Hope this will help somehow.

**Comment by AxelTerizaki** [comment] 2018-07-16 21:39
Ah, just adding something because we just noticed something interesting.

The user was looking at the download bar and at some point, it stalled. However, it did not cause an error or crash on filezilla's end.

```Jul 16 23:26:12 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:26:12 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [retr] [ANG - The Cranberries - MV - Zombie.avi]
Jul 16 23:27:01 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [INFO] New connection from xxx.xxx.xxx.xxx.rev.sfr.net
Jul 16 23:27:02 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [auth] [TLS]
Jul 16 23:27:02 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [auth] [SSL]
Jul 16 23:27:02 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [user] [kmvideos]
Jul 16 23:27:02 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [pass] [<*>]
Jul 16 23:27:02 shelter pure-ftpd: (?@xxx.xxx.xxx.xxx.rev.sfr.net) [INFO] kmvideos is now logged in
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [opts] [UTF8 ON]
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [cwd] [/]
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [type] [I]
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [pasv] []
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [rest] [12803224]
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [NOTICE] Restarting at 12803224
Jul 16 23:27:02 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [DEBUG] Command [retr] [ANG - The Cranberries - MV - Zombie.avi]
Jul 16 23:27:03 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ANG - The Cranberries - MV - Zombie.avi downloaded  (50119528 bytes, 39231.02KB/sec)
Jul 16 23:27:11 shelter pure-ftpd: (kmvideos@xxx.xxx.xxx.xxx.rev.sfr.net) [NOTICE] /home/aterizak/karaokemugen/app/data/medias//ANG - The Cranberries - MV - Zombie.avi downloaded  (16777216 bytes, 278.82KB/sec)
```

Apparently it got stalled at some point, and relogged in automatically to finish the file. 

You were right then, when you said I had to try to handle retries and restarting by myself.

Since the issue isn't happening to me, it's going to be hard to test it out alone...

I don't suppose basic-ftp can implement the retry system itself? Would feel more natural not having to worry about it. Then again, I understand it's quite some work.

**Comment by AxelTerizaki** [comment] 2018-07-17 12:45
Yep, I realize it depends on the scope of the library, and it's up to you to decide that.

I'll have to handle the retry mechanic anyway, the more I think about it, because this can also happen with HTTP downloads as you said it earlier.

Thanks for your patience. If I can help further, don't hesitate to ask.

**Closed** 2018-07-17 12:53 UTC
