### ISSUE TITLE
Error: Client is closed - when trying to attempt to parallel connections transfers

### ISSUE THREAD

**Issue by psr1410** [patrickjuchli/basic-ftp#119] opened 2019-12-26 15:32 UTC
I am doing a migration job from downloading files from FTP to upload it to Azure blob service. It was working fine with 1 FTP client connection. 

To improve the performance I am trying to download the files using parallel connections(2 different connections), but end up getting the `Error: Client is closed` error after completion of some file downloads.

Note: my FTP allowing parallel connections. I am using Node 12.13.0

Below is the full error I am getting. Can you please help me to resolve this issue.

`Error: Client is closed
at /app/node_modules/basic-ftp/dist/FtpContext.js:220:29
at new Promise (<anonymous>)
at FTPContext.handle (/app/node_modules/basic-ftp/dist/FtpContext.js:200:16)
at FTPContext.request (/app/node_modules/basic-ftp/dist/FtpContext.js:177:21)
at Client.enterPassiveModeIPv6 [as prepareTransfer] (/app/node_modules/basic-ftp/dist/transfer.js:10:27)
at Client._downloadToStream (/app/node_modules/basic-ftp/dist/Client.js:425:24)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
Closing reason: Error: This socket has been ended by the other party (control socket)
at Socket.writeAfterFIN [as write] (net.js:442:14)
at FTPContext.send (/app/node_modules/basic-ftp/dist/FtpContext.js:170:22)
at /app/node_modules/basic-ftp/dist/FtpContext.js:230:22
at new Promise (<anonymous>)
at FTPContext.handle (/app/node_modules/basic-ftp/dist/FtpContext.js:200:16)
at FTPContext.request (/app/node_modules/basic-ftp/dist/FtpContext.js:177:21)
at Client.enterPassiveModeIPv6 [as prepareTransfer] (/app/node_modules/basic-ftp/dist/transfer.js:10:27)
at Client._downloadToStream (/app/node_modules/basic-ftp/dist/Client.js:425:24)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5) {
code: 'EPIPE'`

**Comment by patrickjuchli** [comment] 2019-12-26 17:45
By "parallel connections" you mean you're creating two independent instances of `Client` and then you use these two instances to download different files?

The exception is `Client closed` but further down you can find the reason: `Closing reason: Error: This socket has been ended by the other party (control socket)`. Looks like the server has closed the connection.

**Comment by psr1410** [comment] 2019-12-26 19:13
> you're creating two independent instances of `Client` and then you use these two instances to download different files?

Yes.


> Looks like the server has closed the connection.

What can we do to overcome this issue? Do I need to change any settings/configuration at the FTP end OR any code handling solve this issue?

**Comment by patrickjuchli** [comment] 2019-12-26 21:52
You're getting this error "after completion of some file downloads". This makes the reason pretty hard to guess. Is it always after the same files? Some other pattern? After how much time?

Not sure I can help you here. Do you have access to logs of the FTP server?

**Comment by patrickjuchli** [comment] 2019-12-29 17:52
@psr1410, I'll have to close this ticket without more feedback. Right now, this does not look like an issue specific to this library. I can't reproduce the behaviour in my own setup.

**Comment by psr1410** [comment] 2019-12-31 11:53
> You're getting this error "after completion of some file downloads". This makes the reason pretty hard to guess. Is it always after the same files? Some other pattern? After how much time?
> 
> Not sure I can help you here. Do you have access to logs of the FTP server?

I don't have FTP error log access Patrick.

**Comment by patrickjuchli** [comment] 2020-01-01 16:53
The issue is not moving forward, so far it doesn't look like a problem with the library. Reopen, if this changes.

**Closed by patrickjuchli** 2020-01-01 16:53 UTC

**Comment by Rioos** [comment] 2021-01-07 13:53
@psr1410 Did you find what was the issue here?

Just saw that and we've been facing a pretty similar issue here. We have all the logs available here, lmk what could help.
