### ISSUE TITLE
How do i downloadTo a variable so i can insert into mongodb?

### ISSUE THREAD

**Issue by Glutch** [patrickjuchli/basic-ftp#108] opened 2019-11-17 22:15 UTC
i used node-ftp previously but since it has a delay bug with 'end' i switched to basic-ftp. But i can't figure out how do take the writablestream är put it into an variable like i did with node-await

```
client.downloadTo(stream, `WebPictures/${imageName}`)
stream.on('data', chunk => console.log(chunk.length))
stream.on('end', () => console.log('image downloaded'))
```

How do i get this to work?

**Comment by patrickjuchli** [comment] 2019-11-18 07:22
Duplicate of #102.

**Closed by patrickjuchli** 2019-11-18 07:22 UTC
