### ISSUE TITLE
Control Socket Timeout In Electron

### ISSUE THREAD

**Issue by sops21** [patrickjuchli/basic-ftp#46] opened 2019-01-02 02:28 UTC
**Describe the bug**
Control Socket Times out before FTP completes. When uploading a large file, I'm getting the error { error: { ftpSocket: 'control', info: 'socket timeout' } }. I'm running this in a electron.js app. It seems to run fine in a plain node.js app. Any thoughts on why the control might timeout in an electron app, but not a command line app?

**Example code**
If I need to can can provide an example electron app. 

**Console output**
```
  Connected to ***
  < 220 ProFTPD 1.3.5 Server (FTP-Server) [::ffff:***]
  Login security: No encryption
  > USER ***
  < 331 Password required for ***
  > PASS ###
  < 230 User *** logged in
  > TYPE I
  < 200 Type set to I
  > STRU F
  < 200 Structure set to F
  Trying to find optimal transfer strategy...
  > EPSV
  < 229 Entering Extended Passive Mode (|||50575|)
  Optimal transfer strategy found.
  > STOR largefile.mp4
  < 150 Opening BINARY mode data connection for largefile.mp4
  Uploading to ***:50575 (No encryption)
  {info: "socket timeout", ftpSocket: "control"}
 { error: { ftpSocket: 'control', info: 'socket timeout' } }
 { error: { ftpSocket: 'control', info: 'socket timeout' } }
```

**Which version of Node.js are you using?**
Electron: 3.0.10
Node 10.2.0

**Additional context**

**Comment by broofa** [comment] 2019-01-02 19:15
Related to https://github.com/patrickjuchli/basic-ftp/pull/45#discussion_r244639958?

**Comment by broofa** [comment] 2019-01-02 19:21
> why the control might timeout in an electron app

Different default TCP idle timeout for Electron apps? 
Your Electron app running on a device with low bandwidth (causing download to take longer than  on whatever system you're running the node app)?

**Comment by patrickjuchli** [comment] 2019-01-03 21:32
@broofa Control socket timeout detection is suspended during file transfers.

**Comment by sops21** [comment] 2019-01-05 19:03
@patrickjuchli If i watch the FTP server, the file is partially uploaded, but when the transfer fails the file is removed. 

I updated to version 3.0.0 It still errors out. Updated log:

```
 Connected to ***:21
 < 220 ProFTPD 1.3.5 Server (FTP-Server) [::ffff:***]
 Login security: No encryption
 > USER ***
 < 331 Password required for ***
 > PASS ###
 < 230 User *** logged in
 > TYPE I
 < 200 Type set to I
 > STRU F
 < 200 Structure set to F
 Trying to find optimal transfer strategy...
 > EPSV
 < 229 Entering Extended Passive Mode (|||50108|).
 Optimal transfer strategy found.
 > STOR largefile.mp4
 < 150 Opening BINARY mode data connection for largefile.mp4
 Uploading to 69.50.138.39:50108 (No encryption)
app.js:49 Error: Timeout (control socket)
    at Socket.socket.once (***\FtpContext.js:393)
    at Object.onceWrapper (events.js:273)
    at Socket.emit (events.js:182)
    at Socket._onTimeout (net.js:445)
    at ontimeout (timers.js:427)
    at tryOnTimeout (timers.js:289)
    at listOnTimeout (timers.js:252)
    at Timer.processTimers (timers.js:212)
```

**Comment by sops21** [comment] 2019-01-05 19:13
Also if I set the timeout to 0 

`const FTPclient = new ftp.Client(0)`

The transfer completes without the control timeout, but that is not ideal since setting the timeout to 0 also effects the transfer timeout.

**Comment by patrickjuchli** [comment] 2019-01-05 19:47
Interesting. Control socket timeout should be disabled but apparently it isn't.

The whole Electron thing is a bit weird. Maybe this has to do with two different versions of Node? And one of them has some issue with setting/resetting socket timeouts? What exact version of Node is your version of Electron using? If you use a Node release of the exact same version, do you get the same error?

[Here](https://nodejs.org/en/download/releases/) you can get previous releases of Node.js

**Comment by patrickjuchli** [comment] 2019-01-05 19:50
Just saw this here over on the Electron issues:
https://github.com/electron/electron/issues/14915

Disabling socket timeout is done by using `socket.setTimeout(0)`.

**Comment by patrickjuchli** [comment] 2019-01-06 20:52
I'm closing this issue because this is a bug in Electron, not Node.js. This library also doesn't depend on Electron. Feel free to open it if appropriate.

**Closed by patrickjuchli** 2019-01-06 20:52 UTC

**Comment by sops21** [comment] 2019-01-06 22:55
Would it make sense to have 2 separate timeouts, one for the control and one for data?

**Comment by patrickjuchli** [comment] 2019-01-07 07:36
No, I don't think it makes sense.

A timeout is a way to declare a connection to be broken after some time of inactivity. Why would you have different standards for that for control and data connection?

Node.js is a bit tricky because the timeout of a socket starts immediately, even if you as a user don't do anything. Also, in FTP there is the situation that while a file is transferred over one connection (data) the other one sits idle (control). This would also trigger a timeout. I think that's the reason the `ftp` package for example offers different timeouts. But this is more of a hack than a solution.

`basic-ftp` avoids that problem by taking more care of timeouts. Timeout detection is only activated when you are actually doing something and only for one connection at a time. So while a file is transferred over a data connection, it tracks timeout only on the data connection, not on the control connection.

**Comment by patrickjuchli** [comment] 2019-01-07 08:15
You should upvote the Electron issue and focus your energy there. I'll go ahead and post a thumbs up as well.

**Comment by warpdesign** [comment] 2019-02-19 09:14
I may have a weird behavior in my app that may be related to this issue.

When pausing my (Electron) app in a debugger statement, I often get this error later:

> Error: Client is closed
    at Promise (file:///Users/leo/dev/react-ftp/dist/gui.js:29145:29)
    at new Promise (<anonymous>)
    at FTPContext.handle (file:///Users/leo/dev/react-ftp/dist/gui.js:29125:16)
    at Client.send (file:///Users/leo/dev/react-ftp/dist/gui.js:28156:25)
    at Client.cd (file:///Users/leo/dev/react-ftp/dist/gui.js:28241:21)
    at SimpleFtpApi.<anonymous> (file:///Users/leo/dev/react-ftp/dist/gui.js:101052:68)
    at step (file:///Users/leo/dev/react-ftp/dist/gui.js:100927:23)
    at Object.next (file:///Users/leo/dev/react-ftp/dist/gui.js:100908:53)
    at file:///Users/leo/dev/react-ftp/dist/gui.js:100902:71
    at new Promise (<anonymous>)
> Closing reason: Error: Timeout (control socket)
    at Socket.socket.once (file:///Users/leo/dev/react-ftp/dist/gui.js:29214:58)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:445:8)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

The weird thing is that I get it even before the default timeout of `30000` is reached.

This makes debugging a real pain.

**Comment by patrickjuchli** [comment] 2019-02-19 09:42
Yep, sorry about that one. I'm very surprised that `socket.setTimeout` behaves differently in an Electron renderer process. This method is used a lot by this library to disable/enable timeout tracking whenever appropriate.

You have to either disable timeouts and use `new Client(0)`. Or you can try if things work in a non-renderer process. Electron calls this "main" process or something?

**Comment by warpdesign** [comment] 2019-02-19 09:50
Unfortunately, moving ftp handling in the main process would require quite a lot of work.

I checked the issue opened in Electron and unfortunately it seems it is still there in the latest Electron release (4.0). I'll use `new Client(0)` during debugging for now then.

**Comment by warpdesign** [comment] 2019-06-22 22:04
@patrickjuchli The issue in Electron has been confirmed but not fixed yet.

While it's being fixed, there is a workaround here: https://github.com/electron/electron/issues/14915#issuecomment-502607259

Maybe it would be a good idea to add a note about timeout problems in Electron for developers using it?
