### ISSUE TITLE
How to make it works in ActiveMode

### ISSUE THREAD

**Issue by LKTPD** [patrickjuchli/basic-ftp#126] opened 2020-01-15 23:25 UTC
If the FTP server only works in ActiveMode, the connection should be not working properly, how to solve it ? thanks!

As setting in FileZilla, there's an option **Fall back to Active Mode** if the passive mode does not work, could this option be shown in the package ?
<img width="775" alt="Snipaste_2020-01-16_07-21-06" src="https://user-images.githubusercontent.com/20557631/72480112-53e08f00-3831-11ea-9bea-e1cb3e923e4f.png">

**Comment by patrickjuchli** [comment] 2020-01-16 00:01
Duplicate of #25

**Closed by patrickjuchli** 2020-01-16 00:01 UTC
