### ISSUE TITLE
ERR_INTERNAL_ASSERTION' when connect to ftps

### ISSUE THREAD

**Issue by hamid-khakzad** [patrickjuchli/basic-ftp#140] opened 2020-04-30 07:39 UTC
`< 220
> AUTH TLS
< 234 AUTH command ok. Expecting TLS Negotiation.
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (internal/assert.js:14:11)
    at Object.connect (_tls_wrap.js:1553:3)
    at C:\Users\Administrator\Desktop\shepa-settlement\node_modules\basic-ftp\dist\netUtils.js:33:33
    at new Promise (<anonymous>)
    at Object.upgradeSocket (C:\Users\Administrator\Desktop\shepa-settlement\node_modules\basic-ftp\dist\netUtils.js:29:
12)
    at Client.useTLS (C:\Users\Administrator\Desktop\shepa-settlement\node_modules\basic-ftp\dist\Client.js:131:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.access (C:\Users\Administrator\Desktop\shepa-settlement\node_modules\basic-ftp\dist\Client.js:188:13
)
    at async FtpsService.testSettlementRequest (C:\Users\Administrator\Desktop\shepa-settlement\dist\services\FtpsUpload
Service.js:58:17) {
  code: 'ERR_INTERNAL_ASSERTION'
}`

i get this error  when try to connect ftps server
how i can solve this problem?

**Comment by patrickjuchli** [comment] 2020-05-01 08:00
The exception gives a hint, doesn't it? `This is caused by either a bug in Node.js or incorrect usage of Node.js internals. Please open an issue with this stack trace at https://github.com/nodejs/node/issues`.

What version of Node are you using?

**Comment by hamid-khakzad** [comment] 2020-05-02 05:33
12.16.3

**Comment by patrickjuchli** [comment] 2020-05-03 20:00
Again, this exception and its description do not originate from this library. As the exception describes, this is an upstream problem within Node.js and you should open an issue there.

I will close this issue. We can reopen this if you find a hint that this library could help in any way.

**Closed by patrickjuchli** 2020-05-03 20:00 UTC
