### ISSUE TITLE
Question: How do I catch an ECONNRESET error using basic-ftp?

### ISSUE THREAD

**Issue by zrougeau** [patrickjuchli/basic-ftp#225] opened 2022-11-21 19:41 UTC
Hello,

I want my program to continue running after catching ECONNRESET. Here's the error below:

Node.js v17.7.2
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

How do I catch it and have the program continue running? I've already tried try/catch blocks shown below:

 async connect(port,ip_address){
          try{
          await this.client.access({
              port: port,
              host: ip_address,
              secure: false
          })
          }
          catch{
            this.num_of_files_read=0;
            this.files_completed=0;
            return 1
          }
          return 0
 }

**Comment by KEMBL** [comment] 2023-02-23 10:55
As far as I understand it is a socket level error and I do not see where `basic-ftp` gives an access to handle the socket events, so what you can do is to add this block into your program, it should intercept all unhandled exceptions:

      process.on('uncaughtException', (err) => {
        console.error(`Unhandled Exception: `, err);
      });

**Comment by patrickjuchli** [comment] 2023-05-05 07:48
As described at https://github.com/patrickjuchli/basic-ftp#error-handling, all errors are thrown as exceptions. You don't have to think about socket/stream errors. Your code should work, not sure yet why it doesn't. Will have a look.

**Comment by ptorrent** [comment] 2023-06-09 17:20
Hello,

Strange approche , you mean there is no way to get on('error', on('close' ?

```
remote.access({
	host		: xx
      user 		: coxx
	password  	: xx
}).then(function(){

}.bind(this)).catch(function(err){
	//ALL ERROR HERE ?
})
````

**Comment by patrickjuchli** [comment] 2023-06-09 20:27
FTP has more than just 1 socket. So which one do you want to listen on? This library has taken the decision that you as the user want to be an abstraction layer above these kind of details and just write this:

```js
try {
  await client.uploadFrom("README.md", "README_FTP.md")
} catch (err) {
  // Handle the error specific to the above task that you just wanted to do. For example: Retry the upload.
}
```

I'm not sure I understand your example correctly but you don't use one single big catch function for all possible tasks, no. When uploading a file for example, 2 sockets are involved and there are quite a number of things that can go wrong. Errors on both, closing on both, timeouts. One socket saying everything is done, the other one nope. Handling these cases correctly is the point of having an FTP library.

**Comment by ptorrent** [comment] 2023-06-09 20:57
I understand your approach. I just need to know when there is no more connections on the server event if this is 10^1000 sockets.

on('connect ++
on('disconnect' --

I will find an other way..

**Comment by zrougeau** [comment] 2023-06-21 18:49
Sorry for the late reply:

I ended up going with a java library called ftp4j.

Thanks everyone for helping me out, and I do apologize for wasting anyone's time if I have done so.

**Comment by patrickjuchli** [comment] 2023-12-19 15:26
Do I understand correctly that there was an issue catching ECONNRESET while connecting using `this.client.access`? If yes, I'll keep this open for a bit, even though I can't reproduce the issue myself.

**Comment by patrickjuchli** [comment] 2024-01-24 21:20
Closing due to inactivity. Do reopen if there is new information.

**Closed by patrickjuchli** 2024-01-24 21:20 UTC
